In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
df=pd.DataFrame({'area':[2600,3000,3200,3600,4000],'price':[550000,565000,610000,
                                                           680000,725000]})

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.intercept_

180616.43835616432

In [7]:
model.predict([[5000]])

array([859554.79452055])

**Save Model To a File Using Python Pickle**

In [8]:

import pickle

In [9]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [10]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [11]:
mp.coef_


array([135.78767123])

In [12]:
mp.intercept_

180616.43835616432

In [13]:
mp.predict([[5000]])

array([859554.79452055])

**Save Trained Model Using joblib**

In [14]:
from sklearn.externals import joblib


C:\Users\DeLL\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [15]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [16]:

mj = joblib.load('model_joblib')

In [17]:
mj.coef_

array([135.78767123])

In [18]:
mj.intercept_

180616.43835616432

In [19]:
mj.predict([[5000]])


array([859554.79452055])